version: "3.9"  # optional since v1.27.0

services:
  postgres:
    image: docker.io/amd64/postgres:14-alpine
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    command: ["postgres", "-c", "log_statement=all"]

  jaeger:
    image: quay.io/jaegertracing/all-in-one:latest
    restart: always
    environment:
      LOG_LEVEL: debug
      COLLECTOR_OTLP_ENABLED: 'true'
    ports:
      - "${JARGER_WEBUI_PORT:-16686}:16686"
      - "${OTLP_EXPORTER_PORT:-4317}:4317"

  web:
    build:
      context: .
      # args:
      #   IMAGE_VERSION: ${TAG}-${BUILD_ID}
    image: image.local/testruction/mvc-flask-dash
    command: tail -f /dev/null
    ports:
      - "55000:5000"
    environment:
      # Flask
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      # OTLP GRPC
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://localhost:4317}
      OTEL_EXPORTER_OTLP_INSECURE: ${OTEL_EXPORTER_OTLP_INSECURE:-true}
      # Postgres
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    links:
      - jaeger
      - postgres
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./MANIFEST.in:/app/MANIFEST.in
      - ./pyproject.toml:/app/pyproject.toml
      - ./README.md:/app/README.md
      - ./setup.cfg:/app/setup.cfg
      - ./VERSION:/app/VERSION
