Parameters:
  RepoName:
    Description: Nom du dépôt Elastic Container Registry
    Type: String
    Default: testruction/mvc-flask-dash
  
  lifecyclePolicyText:
    Description: Politique de gestion du cycle de vie des OCIs
    Type: String
    Default: |
      {
        "rules": [
          {
            "rulePriority": 1,
            "description": "Remove all untagged images",
            "selection": {
              "tagStatus": "untagged",
              "countType": "imageCountMoreThan",
              "countNumber": 2
            },
            "action": {
              "type": "expire"
            }
          },
          {
            "rulePriority": 99,
            "description": "Only keep 8 images",
            "selection": {
              "tagStatus": "any",
              "countType": "imageCountMoreThan",
              "countNumber": 8
            },
            "action": {
              "type": "expire"
            }
          }
        ]
      }
  
Resources:
  Repo:
    Type: AWS::ECR::Repository
    Properties:
      ImageScanningConfiguration:
        ScanOnPush: True
      ImageTagMutability: MUTABLE
      RepositoryName: !Sub "${RepoName}"
      LifecyclePolicy:
        LifecyclePolicyText: !Ref lifecyclePolicyText
        RegistryId: !Sub "${AWS::AccountId}"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: LambdaECRImageRetrievalPolicy
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - "ecr:BatchGetImage"
              - "ecr:DeleteRepositoryPolicy"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:GetRepositoryPolicy"
              - "ecr:SetRepositoryPolicy"
      Tags:
        - Key: io.testruction.ecr.repository
          Value: !Ref RepoName
